export const logInConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  RECEIVE_JSON: 'RECEIVE_JSON',
  SEND_JSON: 'SEND_JSON',
  RECEIVE_REQUEST: 'RECEIVE_REQUEST',
  SEND_REQUEST: 'SEND_REQUEST',
}
